### PR TITLE
Intraday timeseries spike

### PR DESCRIPTION
**Pull request by jamieinfinity**

### CODE REVIEW

**Comment by brad** [comment]
@jamieinfinity I finally got around to testing this out and it looks good to me with one change:

```python
        if start_time:
            time_init = start_time
            if not isinstance(time_init, str):
                time_init = start_time.strftime('%H:%M')
            url = url + ('/time/%s' % (time_init))
```

The key is the addition of `time/` to the url. Without it, fitbit matches a [different API endpoint](https://wiki.fitbit.com/display/API/API-Browse-Activities) and returns a list of activity categories instead. A couple URLs in the tests also need to be updated because of this. Could you make the change in your branch? If you aren't going to for whatever reason, please just let me know and I'll merge this as is and make the changes on my end. Thanks again!

**Comment by jamieinfinity** [comment]
Thanks Brad, I’ll make this update and push it up on my branch this weekend.

**Comment by brad** [comment]
@jamieinfinity Maybe next weekend? :smile:

**Comment by jamieinfinity** [comment]
Sorry bout that, it’s definitely on my todo for this week. I won’t be offended if you go ahead and make the change...if you don’t get to it, I should find time later this week.

**Comment by brad** [comment]
Thanks @jamieinfinity I went ahead and merged your changes in

**Pull request merged**
