### PR TITLE
change condition for refresh_token() according to expired_token response

### LINKED ISSUE #86: make_request inside FitbitOauth2Client does not handle refresh on expired token correctly
Hi there,

I think there is a problem with token refreshing. On expired_token, _fitbit.exceptions.HTTPUnauthorized: Access token expired_ is still being thrown instead of handled correctly. https://github.com/orcasgit/python-fitbit/blob/master/fitbit/api.py#L82.

Inside the if condition, it checks d['errors'][0]['errorType'] == 'oauth' and ... and calls self.refresh_token() when that condition is met, but the errorType is 'expired_token' not 'oauth'. This is the JSON body:

{u'errors': [{u'errorType': u'expired_token',
              u'message': u'Access token expired: [_omitting_token_string here_]. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process.'}],
 u'success': False}

As a result it's never retried and we get the access token expired exception later again.

Let me know if my understanding of how this works/doesn't work is correct :)...

### PR DESCRIPTION
**Pull request by xuefanzhang**
This fixes #86 .

### CODE REVIEW

**Comment by percyperez** [comment]
Thanks for submitting this PR. I actually was able to re-create the issue. However, while debugging/testing this new code related to [self.token](https://github.com/orcasgit/python-fitbit/pull/87/files#diff-a8b749e0aa1b9f89d4a65033a9e5dfacR164) I get an error
 ```
MissingTokenError: MissingT...meter.',)
> /opt/python-fitbit/fitbit/api.py(169)refresh_token()
-> auth=requests.auth.HTTPBasicAuth(self.client_id, self.client_secret)
```
I'm going to try with your latest commit

**Comment by percyperez** [comment]
@xuefanzhang It looks like I was testing with an invalid token. After testing the code with a "valid" expired token, [refresh_token()](https://github.com/riselabs/python-fitbit/blob/OAuth2RefreshToken/fitbit/api.py#L156) worked as expected. However, this change [HTTPUnauthorized](https://github.com/orcasgit/python-fitbit/pull/87/commits/48169f8bc6ed74f89015ae457449fc8e7449293c) is breaking two tests: `test_auto_refresh_token_exception` and `test_auto_refresh_token_nonException` I think if we can fix the tests, then we should we good to go // cc @brad

**Comment by brad** [comment]
@percyperez If you want to, I think it's reasonable to go ahead and merge
this as is and then fix the tests yourself

**Comment by xuefanzhang** [comment]
Thanks for looking into this @percyperez @brad.

**Comment by isaacnorman82** [comment]
Is this fix still in place?  I just started using the library and it doesn't seem to refresh an expired token.  I ge the 'HTTPUnauthorized: Access token expired' error.  I tried to see if I have the code from this PR in my version but things seem to have changed since.

I have fitbit==0.3.1

Edit:  Sorry I realised my mistake was not providing a refresh_cb.  Perhaps it would be good if there was a log message saying 'not refreshing because there's no cb'.  I'm not sure why the cb isn't mandatory...

**Pull request merged**
