### PR TITLE
Upgrade release version 0.2.3

### PR DESCRIPTION
**Pull request by tchellomello**
Upgrade to release 0.2.3

### CODE REVIEW

**Comment by brad** [comment]
LGTM :shipit:

**Comment by grokcode** [comment]
Thanks @tchellomello! I'll see if I can get this on PyPi today.

**Comment by tchellomello** [comment]
Thank you guys!

**Comment by grokcode** [comment]
Thanks @tchellomello, 0.2.3 is up on PyPi.

**Comment by tchellomello** [comment]
Thanks @grokcode  It is very appreciated!!

**Pull request merged**
