### PR TITLE
Oauth2 dev

### PR DESCRIPTION
**Pull request by randi120**
pull-request with working oauth2 
-additions:
 1. new client class  that uses oauth2 instead of oauth1 "FitbitOauth2Client" 
     -same interface as FitbitOauthClient. 
     -has the ability to generate the authorization url to obtain code.
     -auto-refreshes access tokens based on refresh token provided. 
 2. changed the initialization of Fitbit class to either work with oauth1 or oauth2 depending on the info provided by the user
      -eg, if user provides a client_key it will use oauth1 if user provides client_id it will use oauth2

 3. Provided a new script to get oauth2 tokens "gather_keys_oauth2.py"

### CODE REVIEW

**Comment by brad** [comment]
Hi @randi120 Thank you so much for the pull request! I like the approach, but it looks like the tests are failing. I can't merge this until the tests are successful and we also need some tests for the `FitbitOAuth2Client` class. If you aren't up for that we will still use your code, it just make take a little longer to get merged in.

**Comment by randi120** [comment]
hey @brad, 
First time using tox so trying to make sense out of it.... I think I got it.

The test are failing because in the Fitbit class I assumed that client_key or client_id would always be passed in as an named arguments and not using the dictionary. 

The reasoning behind this was that the Fitbit class has no way of knowing which authentication (oauth1 or oauth2) it's going to use. I tried to automatically figure this out based on the information provided but using the named arguments only. I can add a check for dictionary values and fix this. 

I'll also take a stab at test cases for `FitbitOAuth2Client`. 
First time with unittests as well.... I am new to python

**Comment by randi120** [comment]
getting there ;)
I'll add the tests for `FitbitOAuth2Client` in a little bit

**Comment by randi120** [comment]
@brad almost there, running into some weird behavior with base64 on python 3 and stackoverflow is failing me on this one. any chance you can take a quick look at lines 172 of `api.py`?

**Comment by randi120** [comment]
@brad solved the base64 issue.
However, I am coming across some more weird behavior on 3.2 and 3.4. 
for some reason one of the unittest is failing...

**Comment by randi120** [comment]
@brad should be okay now

**Comment by randi120** [comment]
Hey @brad, any word on this?

**Comment by brad** [comment]
Hi @randi120 haven't forgotten about this, I'll get to it by Friday

**Comment by brad** [comment]
@randi120 I'm mostly happy with the end result, but there are quite a few commits there. Can you do a git rebase and squish them please?

**Comment by randi120** [comment]
done

**Comment by brad** [comment]
I appreciate that so much @randi120. Sorry it's taking so long to merge in, I haven't forgotten about you! Just need a couple more days

**Comment by brad** [comment]
Thank you for your contribution @randi120 :+1:

**Pull request merged**
