### PR TITLE
  Fixes when oauth tokens expired and fetches a new token.

### PR DESCRIPTION
**Pull request by tchellomello**
Sometimes fitbit raises an exception. 

This patch catch the exception and fetches a new token.

### CODE REVIEW

**Comment by brad** [comment]
LGTM. Can I get one more approval @grokcode @percyperez ?

**Comment by grokcode** [comment]
LGTM too. Thanks for the fix @tchellomello!

**Comment by tchellomello** [comment]
Hello @grokcode @brad  Thanks for approving the PR. 

Would be possible to bump the release as well? I'm working on another patch to another project where I would like to force this specific version on the requirements.txt

**Comment by tchellomello** [comment]
@grokcode  @brad  guys, I've added a new PR to increase the release at https://github.com/orcasgit/python-fitbit/pull/99 

Thank you!

**Pull request merged**
